import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";

const API_KEY = "0db69991ed83415fa6f591a1924e45ef";
const BASE_URL =
  "https://newsapi.org/v2/top-headlines?category=business&apiKey=";

// Async thunk for fetching business news
export const fetchNews = createAsyncThunk(
  "news/fetchNews",
  async (thunkAPI) => {
    try {
      // Fetch data from NewsAPI
      const response = await fetch(`${BASE_URL}${API_KEY}`);
      const data = await response.json();
      console.log("News API response", data);
      return data;
    } catch (error) {
      return thunkAPI.rejectWithValue(error.message);
    }
  }
);

// Define the slice for managing news state in the Redux store
const newsSlice = createSlice({
  name: "news",
  initialState: {
    news: null,
    loading: false,
    error: null,
  },
  reducers: {}, // No additional reducers are needed in this case
  extraReducers: (builder) => {
    // Handle actions generated by the async thunk (fetchNews)
    builder
      .addCase(fetchNews.pending, (state) => {
        // When the fetch is pending, set the loading state to true
        state.loading = true;
        state.error = null; // Clear any previous errors
      })
      .addCase(fetchNews.fulfilled, (state, action) => {
        // If the fetch is successful, update the state with the fetched data
        state.loading = false;
        state.news = action.payload;
      })
      .addCase(fetchNews.rejected, (state, action) => {
        // If the fetch fails, set the loading state to false and record the error
        state.loading = false;
        state.error = action.payload;
      });
  },
});

export default newsSlice.reducer;
