const nasdaqCompanies = [
    { name: "Apple", symbol: "AAPL" },
    { name: "Microsoft", symbol: "MSFT" },
    { name: "Tesla", symbol: "TSLA" },
    { name: "Amazon", symbol: "AMZN" },
    { name: "Google", symbol: "GOOGL" },
    { name: "Meta", symbol: "META" },
    { name: "Nvidia", symbol: "NVDA" },
    { name: "Netflix", symbol: "NFLX" },
    { name: "Adobe", symbol: "ADBE" },
    { name: "PayPal", symbol: "PYPL" },
    { name: "Intel", symbol: "INTC" },
    { name: "Cisco", symbol: "CSCO" },
    { name: "Broadcom", symbol: "AVGO" },
    { name: "Qualcomm", symbol: "QCOM" },
    { name: "Starbucks", symbol: "SBUX" },
    { name: "PepsiCo", symbol: "PEP" },
    { name: "Moderna", symbol: "MRNA" },
    { name: "Zoom Video", symbol: "ZM" },
    { name: "Booking Holdings", symbol: "BKNG" },
    { name: "eBay", symbol: "EBAY" },
    { name: "Dell Technologies", symbol: "DELL" },
    { name: "AMD", symbol: "AMD" },
    { name: "Marvell Technology", symbol: "MRVL" },
    { name: "Intuit", symbol: "INTU" },
    { name: "Tesla", symbol: "TSLA" },
    { name: "Lam Research", symbol: "LRCX" },
    { name: "Costco", symbol: "COST" },
    { name: "DexCom", symbol: "DXCM" },
    { name: "Illumina", symbol: "ILMN" },
    { name: "Micron Technology", symbol: "MU" },
    { name: "ASML Holding", symbol: "ASML" },
    { name: "Pinduoduo", symbol: "PDD" },
    { name: "NXP Semiconductors", symbol: "NXPI" },
    { name: "Regeneron Pharmaceuticals", symbol: "REGN" },
    { name: "Workday", symbol: "WDAY" },
    { name: "KLA Corporation", symbol: "KLAC" }
    ];
  
  export default nasdaqCompanies;